server:
  port: 8222
  servlet:
    session:
      timeout: 10800m

forest:
  log-response-content: true
  variables:
    giteye:
      giteeClientId: ${giteye.gitee-client-id}
      giteeClientSecret: ${giteye.gitee-client-secret}
      giteeBaseUrl: ${giteye.gitee-base-url}
      giteeCallbackUrl: ${giteye.gitee-callback-url}
    wxmp:
      wxmpBaseUrl: https://api.weixin.qq.com
      appId: ${giteye.wxmp-app-id}
      secret: ${giteye.wxmp-secret}
      starTemplateId: ${giteye.star-template-id}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/giteye_dev?useUnicode=true&characterEncoding=utf-8&connectTimeout=6000&socketTimeout=6000&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: giteye_dev
    password: [password]
    druid:
      max-wait: 30000
      initial-size: 5
      max-active: 20
      min-idle: 10
      validation-query: select 1
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  lifecycle:
    timeout-per-shutdown-phase: 30s
  redis:
    host: [host]
    port: 6379
    password: [password]
    jedis:
      pool:
        max-active: 20
        min-idle: 3
        max-idle: 10
    timeout: 5000
    database: 1
  session:
    store-type: redis

giteye:
  wxmp-token: [wxmp-token]
  #  wxmp-encoding-aes-key: [wxmp-encoding-aes-key]
  wxmp-app-id: [wxmp-app-id]
  wxmp-secret: [wxmp-secret]
  gitee-base-url: https://gitee.com
  gitee-auth-url: https://gitee.com/oauth/authorize
  gitee-callback-url: https://dev.api.giteye.net/notify/gitee
  gitee-redirect-url: https://dev.giteye.net/my/gitee
  gitee-client-id: [gitee-client-id]
  gitee-client-secret: [gitee-client-secret]
  headless-chrome-driver: /data/headless-chrome/chromedriver
  chart-web-width: 2048
  chart-web-height: 1536
  session-domain: giteye.net
  default-auth-user-id: 19
  star-template-id: [star-template-id]
  cookie-data: [cookie-data]

qcloud:
  secret-id: [secret-id]
  secret-key: [secret-key]
  cos-region-id: ap-shanghai
  cos-gitee-bucket: [cos-gitee-bucket]
  cos-base-url: https://chart-dev.giteye.net
  chart-url: http://dev.giteye.net/private

